name: RHEL-RPM-Collection (Branch)
run-name: ${{ github.actor }} is Collecting Images with Branch 🚀
on:
  push:
    branches-ignore:
      - main
  release:
    types: [edited, released]
  workflow_dispatch:

jobs:
  Date:
    runs-on: ubuntu-24.04
    outputs:
      Date: ${{ steps.date.outputs.date }}
    steps:
      - name: Get current date
        id: DATE
        run: |
          echo "Setting Date"
          echo "DATE=$(date '+%Y%m%d-%H%M')" >> $GITHUB_OUTPUT
          echo -e "\nWrote to file:\n$GITHUB_OUTPUT\n"
          echo "Values:"
          cat $GITHUB_OUTPUT

      - name: Get disk space
        id: DISK  
        run: |
          df -h
          echo -e "\nDisk List"
          sudo fdisk -l | grep -i disk

  Collect-RPMs:
    needs: [Date]
    runs-on: ubuntu-24.04
    strategy:
        max-parallel: 1
        matrix:
            os: [8, 9]
            # repo: [rhel-${{ matrix.os }}-for-x86_64-baseos-rpms, rhel-${{ matrix.os }}-for-x86_64-appstream-rpms, codeready-builder-for-rhel-${{ matrix.os }}-x86_64-rpms, epel, docker-ce-stable]
            repo: [rhel-matrix-for-x86_64-baseos-rpms]
    container:
      image: docker.io/redhat/ubi${{ matrix.os }}
      env:
        GH_TOKEN: ${{ github.token }}
      volumes:
        - /mnt:/mnt
      # credentials:
      #   username: ${{ secrets.REGISTRY_USER }}
      #   password: ${{ secrets.REGISTRY_TOKEN }}
      # ports:
      #   - 80

    env:
      GH_TOKEN: ${{ github.token }}

    steps:
      - name: Check for dockerenv file
        run: (ls /.dockerenv && echo Found dockerenv) || (echo No dockerenv)
      
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Show Files
        run: |
          chmod a+x reposync.sh 
          ls -Alht

      - name: List disks
        run: df -h /mnt

      - name: Register system and install packages
        run: |
          rm /etc/rhsm-host
          subscription-manager register --username '${{ secrets.RHDN_USER }}' --password '${{ secrets.RHDN_PASS }}'
          dnf install -y dnf-plugins-core yum-utils mkisofs isomd5sum tree procps-ng
          echo "Registering epel Repo"
          dnf install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-${{ matrix.os }}.noarch.rpm
          echo "Registering docker-ce-stable Repo"
          dnf config-manager --add-repo https://download.docker.com/linux/rhel/docker-ce.repo

      - name: Run Collection for ${{ matrix.repo }}
        run: |
          export REPO=${{ matrix.repo }}
          REPO=${REPO/matrix/${{ matrix.os }}}
          echo -e "\nWorking on repo $REPO\n"
          echo "Collecting $REPO RPMs"
          ./reposync.sh $REPO

      - name: Upload reposync log
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.repo }}-${{ matrix.os }}-${{ needs.Date.outputs.Date }}.log
          path: ${{ matrix.repo }}.log
          if-no-files-found: error

      - name: Unregister system
        run: subscription-manager unregister

      - name: Show Consumption
        run: |
          echo -e "Disk Usage $(du -chs /mnt/${{ matrix.repo }})\n"
          echo -e "Disk Space $(df -h /mnt/)"

      # - name: Copy README to ${{ matrix.repo }} ISO
      #   run: cp -v README.md /mnt/${{ matrix.repo }}/

      - name: ISO Table of contents
        run: |
          tree /mnt/${{ matrix.repo }} \
            | tee /mnt/${{ matrix.repo }}/${{ matrix.repo }}-${{ matrix.os }}-${{ needs.Date.outputs.Date }}.iso.txt

      - name: Upload ISO ToC artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.repo }}-${{ matrix.os }}-${{ needs.Date.outputs.Date }}.iso.txt
          path: /mnt/${{ matrix.repo }}/${{ matrix.repo }}-${{ matrix.os }}-${{ needs.Date.outputs.Date }}.iso.txt
          if-no-files-found: error

      - name: Make ${{ matrix.repo }} ISO
        run: |
          echo "Making ISO of ${{ matrix.repo }}"
          mkisofs -J -R -v -T -l \
            -V '${{ matrix.repo }}-${{ needs.Date.outputs.Date }}' \
            -A '${{ matrix.repo }}-${{ needs.Date.outputs.Date }}' \
            -o /mnt/${{ matrix.repo }}-${{ matrix.os }}-${{ needs.Date.outputs.Date }}.iso \
            /mnt/${{ matrix.repo }}

      - name: Implant MD5 sum into ${{ matrix.repo }}-${{ matrix.os }}-${{ needs.Date.outputs.Date }}.iso
        run: implantisomd5 /mnt/${{ matrix.repo }}-${{ matrix.os }}-${{ needs.Date.outputs.Date }}.iso

      - name: Generate ${{ matrix.repo }}-${{ matrix.os }}-${{ needs.Date.outputs.Date }}.iso Hash
        run: |
          sha256sum -b /mnt/${{ matrix.repo }}-${{ matrix.os }}-${{ needs.Date.outputs.Date }}.iso | tee \
            /mnt/${{ matrix.repo }}-${{ matrix.os }}-${{ needs.Date.outputs.Date }}.iso.sha

      - name: Show ISO & Hash
        run: ls -Alh /mnt/*.iso*

      - name: Upload ISO
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.repo }}-${{ matrix.os }}-${{ needs.Date.outputs.Date }}.iso
          path: /mnt/${{ matrix.repo }}-${{ matrix.os }}-${{ needs.Date.outputs.Date }}.iso
          if-no-files-found: error

      - name: Upload ISO Hash
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.repo }}-${{ matrix.os }}-${{ needs.Date.outputs.Date }}.iso.sha
          path: /mnt/${{ matrix.repo }}-${{ matrix.os }}-${{ needs.Date.outputs.Date }}.iso.sha

      - name: Clean up
        run: |
          echo "Remove ${{ matrix.repo }}"
          rm -rf /mnt/${{ matrix.repo }}
          echo "Remove Artifacts"
          rm -rfv /mnt/${{ matrix.repo }}-${{ matrix.os }}-${{ needs.Date.outputs.Date }}.iso
          rm -rfv /mnt/${{ matrix.repo }}-${{ matrix.os }}-${{ needs.Date.outputs.Date }}.iso.sha
          rm -rfv /mnt/${{ matrix.repo }}-${{ matrix.os }}-${{ needs.Date.outputs.Date }}.iso.txt
          echo "Done"