name: RHEL-RPM-Collection
run-name: ${{ github.actor }} is Collecting Images 🚀
on:
  push:
    branches-ignore:
      - main
  release:
    types: [edited, released]
  workflow_dispatch:

jobs:
  Date:
    runs-on: ubuntu-24.04
    outputs:
      Date: ${{ steps.date.outputs.date }}
    steps:
      - name: Get current date
        id: DATE
        run: |
          echo "Setting Date"
          echo "DATE=$(date '+%Y%m%d-%H%M')" >> $GITHUB_OUTPUT
          echo -e "\nWrote to file:\n$GITHUB_OUTPUT\n"
          echo "Values:"
          cat $GITHUB_OUTPUT

      - name: Get disk space
        id: DISK  
        run: |
          df -h
          echo -e "\nDisk List"
          sudo fdisk -l | grep -i disk

  Collect-RPMs-RHEL8:
    needs: [Date]
    runs-on: ubuntu-24.04
    container:
      image: docker.io/redhat/ubi8
      env:
        NODE_ENV: development
        GH_TOKEN: ${{ github.token }}
      # credentials:
      #   username: ${{ secrets.REGISTRY_USER }}
      #   password: ${{ secrets.REGISTRY_TOKEN }}

      # ports:
      #   - 80
      # volumes:
      #   - my_docker_volume:/volume_mount
    env:
      GH_TOKEN: ${{ github.token }}
    strategy:
        max-parallel: 1
        matrix:
            # set: [CoreOS, Appstream, CodeReady, EPEL, Docker]
            set: [Docker]
    steps:
      - name: Check for dockerenv file
        run: (ls /.dockerenv && echo Found dockerenv) || (echo No dockerenv)
      
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Show Files
        run: ls -Alht

      - name: List disks
        run: df -h /

      - name: Register system and install packages
        run: |
          rm /etc/rhsm-host
          subscription-manager register --username '${{ secrets.RHDN_USER }}' --password '${{ secrets.RHDN_PASS }}'
          dnf install -y dnf-plugins-core yum-utils mkisofs isomd5sum tree procps-ng

      - name: Run Collection for ${{ matrix.set }}
        run: |
          case ${{ matrix.set }} in
            CoreOS)
              echo "Collecting CoreOS RPMs"
              reposync --download-metadata \
                --repo=rhel-8-for-x86_64-baseos-rpms \
                -p /mnt/${{ matrix.set }} > ${{ matrix.set }}.log &
              pid=$!
              echo "Process $pid is running"
              while kill -0 $pid 2>/dev/null; do
                free -h | awk 'NR==2 {print $4}'
                df -h /mnt | awk 'NR==2 {print $4}'
                tail -n 1 ${{ matrix.set }}.log
                sleep 10
                sleep 10
              done
              echo "Process $pid is Complete"
            ;;
            Appstream)
              echo "Collecting Appstream RPMs"
              reposync --download-metadata \
                --repo=rhel-8-for-x86_64-appstream-rpms \
                -p /mnt/${{ matrix.set }} &
                pid=$!
              echo "Process $pid is running"
              while kill -0 $pid 2>/dev/null; do
                free -h | awk 'NR==2 {print $4}'
                df -h /mnt | awk 'NR==2 {print $4}'
                tail -n 1 ${{ matrix.set }}.log
                sleep 10
              done
              echo "Process $pid is Complete"
              ;;
            CodeReady)
              echo "Collecting CodeReady Builder RPMs"
              reposync --download-metadata \
                --repo=codeready-builder-for-rhel-8-x86_64-rpms \
                -p /mnt/${{ matrix.set }} &
                pid=$!
              echo "Process $pid is running"
              while kill -0 $pid 2>/dev/null; do
                free -h | awk 'NR==2 {print $4}'
                df -h /mnt | awk 'NR==2 {print $4}'
                tail -n 1 ${{ matrix.set }}.log
                sleep 10
              done
              echo "Process $pid is Complete"
              ;;
            EPEL)
              echo "Registering EPEL Repo"
              dnf install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
              echo "Collecting EPEL RPMs"
              reposync --download-metadata \
                --repo=epel \
                -p /mnt/${{ matrix.set }} &
                pid=$!
              echo "Process $pid is running"
              while kill -0 $pid 2>/dev/null; do
                free -h | awk 'NR==2 {print $4}'
                df -h /mnt | awk 'NR==2 {print $4}'
                tail -n 1 ${{ matrix.set }}.log
                sleep 10
              done
              echo "Process $pid is Complete"
              ;;
            Docker)
              echo "Registering Docker CE Repo"
              dnf config-manager --add-repo https://download.docker.com/linux/rhel/docker-ce.repo
              echo "Collecting Docker RPMs"
              reposync --download-metadata \
                --repo=docker-ce-stable \
                -p /mnt/${{ matrix.set }} &
                pid=$!
              echo "Process $pid is running"
              while kill -0 $pid 2>/dev/null; do
                free -h | awk 'NR==2 {print $4}'
                df -h /mnt | awk 'NR==2 {print $4}'
                tail -n 1 ${{ matrix.set }}.log
                sleep 10
              done
              echo "Process $pid is Complete"
              ;;
            *)
              echo "No valid set found"
              ;;
          esac

      - name: Unregister system
        run: subscription-manager unregister

      - name: Show Consumption
        run: |
          echo -e "Disk Usage $(du -chs ${{ matrix.set }})\n"
          echo -e "Disk Space $(df -h /)\n"

      - name: Copy README to ${{ matrix.set }} ISO
        run: cp -v README.md ${{ matrix.set }}/

      - name: ISO Table of contents
        run: |
          tree ${{ matrix.set }} \
            | tee ${{ matrix.set }}/${{ matrix.set }}-${{ needs.Date.outputs.Date }}.iso.txt

      - name: Upload ISO ToC artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.set }}-${{ needs.Date.outputs.Date }}.iso.txt
          path: ${{ matrix.set }}/${{ matrix.set }}-${{ needs.Date.outputs.Date }}.iso.txt
          if-no-files-found: error

      - name: Make ${{ matrix.set }} ISO
        run: |
          echo "Making ISO of ${{ matrix.set }}"
          mkisofs -J -R -v -T -l \
            -V '${{ matrix.set }}-${{ needs.Date.outputs.Date }}' \
            -A '${{ matrix.set }}-${{ needs.Date.outputs.Date }}' \
            -o ${{ matrix.set }}-${{ needs.Date.outputs.Date }}.iso \
            ${{ matrix.set }}

      - name: Implant MD5 sum into ${{ matrix.set }}-${{ needs.Date.outputs.Date }}.iso
        run: implantisomd5 ${{ matrix.set }}-${{ needs.Date.outputs.Date }}.iso

      - name: Generate ${{ matrix.set }}-${{ needs.Date.outputs.Date }}.iso Hash
        run: |
          sha256sum -b ${{ matrix.set }}-${{ needs.Date.outputs.Date }}.iso | tee \
            ${{ matrix.set }}-${{ needs.Date.outputs.Date }}.iso.sha

      - name: Show ISO & Hash
        run: ls -Alh *.iso*

      - name: Upload ISO
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.set }}-${{ needs.Date.outputs.Date }}.iso
          path: ${{ matrix.set }}-${{ needs.Date.outputs.Date }}.iso
          if-no-files-found: error

      - name: Upload ISO Hash
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.set }}-${{ needs.Date.outputs.Date }}.iso.sha
          path: ${{ matrix.set }}-${{ needs.Date.outputs.Date }}.iso.sha
