name: RHEL-RPM-Collection (Full)
run-name: ${{ github.actor }} is Collecting All the RPMS 🚀
on:
  push:
    branches:
      - full
  schedule:
    - cron: "0 0 1 1,4,7,10 *" # Update Quarterly on the 1st
  workflow_dispatch:

jobs:
  Date:
    runs-on: ubuntu-24.04
    outputs:
      Date: ${{ steps.date.outputs.date }}
    steps:
      - name: Get current date
        id: DATE
        run: |
          echo "Setting Date"
          echo "DATE=$(date '+%Y%m%d-%H%M')" >> $GITHUB_OUTPUT
          echo -e "\nWrote to file:\n$GITHUB_OUTPUT\n"
          echo "Values:"
          cat $GITHUB_OUTPUT

      - name: Get disk space
        id: DISK  
        run: |
          df -h
          echo -e "\nDisk List"
          sudo fdisk -l | grep -i disk
          echo -e "\nPermissions on /mnt"
          ls -alht /mnt

  Collect-RPMs:
    needs: [Date]
    runs-on: linux-300G
    strategy:
        max-parallel: 1
        matrix:
            os: [8, 9]
            repo: [rhel-matrix-for-x86_64-baseos-rpms, rhel-matrix-for-x86_64-appstream-rpms, codeready-builder-for-rhel-matrix-x86_64-rpms, epel, docker-ce-stable, hashicorp]
    container:
      image: docker.io/redhat/ubi${{ matrix.os }}
      env:
        GH_TOKEN: ${{ github.token }}
      # volumes:
      #   - $PWD:/mnt
      # credentials:
      #   username: ${{ secrets.REGISTRY_USER }}
      #   password: ${{ secrets.REGISTRY_TOKEN }}
      # ports:
      #   - 80

    steps:
      - name: Check for dockerenv file
        run: (ls /.dockerenv && echo Found dockerenv) || (echo No dockerenv)
      
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Show Files
        run: ls -Alht

      - name: List disks
        run: df -h 

      - name: Setup Path
        run: echo "PATH=$PATH:$PWD/scripts" >> $GITHUB_ENV

      - name: Register system and install packages
        run: ./scripts/registerubi.sh '${{ secrets.RHDN_USER }}' '${{ secrets.RHDN_PASS }}'

      - name: Set Dynamic Repo Names
        id: set_repo
        run: |
          export REPO=${{ matrix.repo }}
          REPO=${REPO/matrix/${{ matrix.os }}}
          echo -e "\nWorking on repo $REPO\n"
          echo "REPO=$REPO" >> $GITHUB_ENV
          echo "Build short repo name"
          case $REPO in
            *"baseos"*) SHORT_REPO="BaseOS${{ matrix.os }}" ;;
            *"appstream"*) SHORT_REPO="AppStream${{ matrix.os }}" ;;
            *"codeready-builder"*) SHORT_REPO="CRB${{ matrix.os }}" ;;
            *"epel"*) SHORT_REPO="EPEL${{ matrix.os }}" ;;
            *"docker-ce-stable"*) SHORT_REPO="Docker${{ matrix.os }}" ;;
          esac
          echo "SHORT_REPO=$SHORT_REPO"
          echo "SHORT_REPO=$SHORT_REPO" >> $GITHUB_ENV

      - name: Run Collection for ${{ env.REPO }}
        run: |
          echo "Collecting repo ${{ env.REPO }} RPMs"
          reposync-all.sh ${{ env.REPO }}
          echo "Logfile: $(ls -1Ssh *.log)"

      - name: Upload reposync log
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.REPO }}-${{ matrix.os }}-${{ needs.Date.outputs.Date }}.log
          path: ${{ env.REPO }}.log
          if-no-files-found: error

      - name: Unregister system
        run: subscription-manager unregister

      - name: Show Consumption
        run: |
          echo -e "Disk Usage $(du -chs ${{ env.REPO }})\n"
          echo -e "Disk Space $(df -h )"


      # - name: Copy README to ${{ env.REPO }} ISO
      #   run: cp -v README.md ${{ env.REPO }}/

      - name: Repo Table of contents
        run: |
          tree ${{ env.REPO }} \
            | tee ${{ env.REPO }}/${{ env.REPO }}-${{ matrix.os }}-${{ needs.Date.outputs.Date }}.iso.txt

      - name: Upload ISO ToC artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.REPO }}-${{ matrix.os }}-${{ needs.Date.outputs.Date }}.iso.txt
          path: ${{ env.REPO }}/${{ env.REPO }}-${{ matrix.os }}-${{ needs.Date.outputs.Date }}.iso.txt
          if-no-files-found: error

      - name: Make ${{ env.REPO }} ISO
        run: |
          echo "Making ISOs of ${{ env.REPO }}"
          chunkiso.sh ${{ env.REPO }} ${{ needs.Date.outputs.Date }}

      - name: Show ISO & Hash
        run: ls -sS1h *.iso*

      - name: Upload ISO SHA artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.REPO }}-${{ matrix.os }}-${{ needs.Date.outputs.Date }}.iso.sha
          path: *.sha
          if-no-files-found: error

      # Send Artifacts to Sharepoint
      - name: Send ${{ env.REPO }} ISO artifacts to Sharepoint
        uses: amentumcms/sharepoint-file-upload-action@main
        with:
          file_path: "*.iso*"
          host_name: "${{ secrets.SHAREPOINT_HOST }}"
          site_name: "${{ secrets.SHAREPOINT_SITE }}"
          upload_path: "${{ secrets.SHAREPOINT_BASEPATH }}/${{ vars.COLLECTOR }}/${{ needs.Date.outputs.Date }}"
          tenant_id: ${{ secrets.SHAREPOINT_TENANT_ID }}
          client_id: ${{ secrets.SHAREPOINT_APP_ID }}
          client_secret: ${{ secrets.SHAREPOINT_APP_SECRET }}
          login_endpoint: "login.microsoftonline.us"
          graph_endpoint: "graph.microsoft.us"

      # Cleanup
      - name: Clean up
        run: |
          cd ${{ env.WORKDIR }}
          echo "Remove ${{ env.REPO }}"
          rm -rf ${{ env.REPO }}
          echo "Remove Artifacts"
          rm -rfv ${{ env.REPO }}-${{ matrix.os }}-${{ needs.Date.outputs.Date }}*.iso
          rm -rfv ${{ env.REPO }}-${{ matrix.os }}-${{ needs.Date.outputs.Date }}*.iso.sha
          rm -rfv ${{ env.REPO }}-${{ matrix.os }}-${{ needs.Date.outputs.Date }}*.iso.txt
          echo "Done"

  # Release:
  #   runs-on: ubuntu-24.04
  #   needs: [Date, Collect-RPMs]
  #   permissions:
  #     contents: write
  #     pull-requests: read
  #   env:
  #     GH_TOKEN: ${{ github.token }}
  #   steps:
  #     - name: Check out repository code
  #       uses: actions/checkout@v4

  #     - name: Download Artifacts
  #       uses: actions/download-artifact@v4
  #       with:
  #         merge-multiple: true
  #         pattern: "*.iso.*"

  #     - name: Show Artifacts
  #       run: ls -sS1h *.iso.*

  #     # Section to actually create a release
  #     - name: Set up git
  #       run: |
  #         git config user.name "$(git log -n 1 --pretty=format:%an)"
  #         git config user.email "$(git log -n 1 --pretty=format:%ae)"

  #     - name: Create tag
  #       uses: rickstaa/action-create-tag@v1
  #       id: tag_create
  #       with:
  #         tag: ${{ needs.Date.outputs.Date }}-Full
  #         github_token: ${{secrets.GITHUB_TOKEN}}
  #         tag_exists_error: false
  #         message: "Release for ${{ needs.Date.outputs.Date }} Full run"

  #     - name: Create Release
  #       id: create_release
  #       uses: softprops/action-gh-release@v2
  #       with:
  #         name: ${{ vars.COLLECTOR }}-Full ${{ needs.Date.outputs.Date }}
  #         tag_name: ${{ needs.Date.outputs.Date }}-Full
  #         make_latest: true
  #         files: |
  #           /mnt/*.iso.*

